"""Константы."""
MAX_LEN_NAME_GATEGORY = 256
MAX_LEN_SLUG = 50
MAX_LEN_NAME_GENRE = 75
MAX_LEN_NAME_TITLE = 150
MAX_LEN_ROLE_USER = 50
MAX_LEN_CODE_USER = 256
LEN_CODE_USER = 20
MAX_LEN_EMAIL = 254
MAX_LEN_USERNAME = 150

RESTRICTED_USERNAMES = ['me', 'admin', 'null']
